import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container mx-auto w-6/12'>
          <nav className='flex flex-wrap items-center justify-center mx-auto p-8'>
            <Link href='/' className='font-bold text-3xl text-blue-600'>
              Snippet
            </Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
